//go:build ignore

package main

import (
	"bytes"
	"crypto/sha256"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

const commit = "7dcb2f4a9e6f7ccfa6b199342aeb95861dc57885"

func main() {
	licensePath := mustLocate("tmp/go264-mit/oxideav-aac/LICENSE")
	spectrumPath := mustLocate("tmp/go264-mit/oxideav-aac/src/spectrum_huffman.rs")
	scalefactorPath := mustLocate("tmp/go264-mit/oxideav-aac/src/scale_factor_data.rs")
	outPath := filepath.Join(mustPackageDir(), "tables_mit.go")

	licenseText := mustRead(licensePath)
	spectrum := mustRead(spectrumPath)
	scalefactor := mustRead(scalefactorPath)
	for _, item := range []struct{ text, hash string }{{licenseText, "4ecae6b086e0d2663c8629e7d3d7ab7d8b39958e8853f9e1371159499a0c3bf2"}, {spectrum, "8fbae6883d3a96f967b4e70f11dd13169c9be6173c9204f8a97d456639af3bc9"}, {scalefactor, "4636a8480f4545e09573e6a49a73ca69f4e244f0a4020d2482e4be5c6e89dbd8"}} {
		if fmt.Sprintf("%x", sha256.Sum256([]byte(item.text))) != item.hash {
			fatalf("reference checksum mismatch")
		}
	}

	tables := []struct {
		name      string
		goName    string
		src       string
		data      string
		dimension int
		lav       int
		unsigned  bool
	}{
		{"HCOD1", "spectralHCOD1", spectrumPath, spectrum, 4, 1, false},
		{"HCOD2", "spectralHCOD2", spectrumPath, spectrum, 4, 1, false},
		{"HCOD3", "spectralHCOD3", spectrumPath, spectrum, 4, 2, true},
		{"HCOD4", "spectralHCOD4", spectrumPath, spectrum, 4, 2, true},
		{"HCOD5", "spectralHCOD5", spectrumPath, spectrum, 2, 4, false},
		{"HCOD6", "spectralHCOD6", spectrumPath, spectrum, 2, 4, false},
		{"HCOD7", "spectralHCOD7", spectrumPath, spectrum, 2, 7, true},
		{"HCOD8", "spectralHCOD8", spectrumPath, spectrum, 2, 7, true},
		{"HCOD9", "spectralHCOD9", spectrumPath, spectrum, 2, 12, true},
		{"HCOD10", "spectralHCOD10", spectrumPath, spectrum, 2, 12, true},
		{"HCOD11", "spectralHCOD11", spectrumPath, spectrum, 2, 16, true},
		{"HCOD_SF", "scalefactorHCOD", scalefactorPath, scalefactor, 0, 0, false},
	}

	var out bytes.Buffer
	fmt.Fprintln(&out, "// Code generated by scripts/gen_audio_huffman.go; DO NOT EDIT.")
	fmt.Fprintln(&out, "//")
	fmt.Fprintln(&out, "// Mechanically ported from the MIT-licensed OxideAV AAC reference:")
	fmt.Fprintf(&out, "//   https://github.com/OxideAV/oxideav-aac/blob/%s/src/spectrum_huffman.rs\n", commit)
	fmt.Fprintf(&out, "//   https://github.com/OxideAV/oxideav-aac/blob/%s/src/scale_factor_data.rs\n", commit)
	fmt.Fprintf(&out, "//   commit %s\n", commit)
	fmt.Fprintln(&out, "//")
	for _, line := range strings.Split(strings.TrimRight(licenseText, "\n"), "\n") {
		if line == "" {
			fmt.Fprintln(&out, "//")
			continue
		}
		fmt.Fprintf(&out, "// %s\n", line)
	}
	fmt.Fprintln(&out)
	fmt.Fprintln(&out, "package huffman")
	fmt.Fprintln(&out)

	for _, table := range tables {
		entries := parseTable(table.data, table.name)
		fmt.Fprintf(&out, "var %s = [...]tableEntry{\n", table.goName)
		for i, entry := range entries {
			fmt.Fprintf(&out, "\t{bits: %s, code: %s}, // %d\n", entry.bits, normalizeCode(entry.code), i)
		}
		fmt.Fprintln(&out, "}")
		fmt.Fprintln(&out)
		if table.dimension != 0 {
			fmt.Fprintf(&out, "var spectralTuples%s = [...][4]int16{\n", strings.TrimPrefix(table.name, "HCOD"))
			for i := range entries {
				values := decodeTuple(i, table.dimension, table.lav, table.unsigned)
				fmt.Fprintf(&out, "\t{%d, %d, %d, %d}, // %d\n", values[0], values[1], values[2], values[3], i)
			}
			fmt.Fprintln(&out, "}")
			fmt.Fprintln(&out)
		}
	}

	formatted, err := format.Source(out.Bytes())
	must(err)
	must(os.WriteFile(outPath, formatted, 0o644))
}

type entry struct {
	bits string
	code string
}

func parseTable(src, name string) []entry {
	marker := "const " + name
	start := strings.Index(src, marker)
	if start < 0 {
		fatalf("table %s not found", name)
	}
	rest := src[start:]
	eq := strings.Index(rest, "= [")
	if eq < 0 {
		fatalf("table %s body start not found", name)
	}
	bodyStart := start + eq + len("= [")
	bodyEnd := strings.Index(src[bodyStart:], "];")
	if bodyEnd < 0 {
		fatalf("table %s body end not found", name)
	}
	body := src[bodyStart : bodyStart+bodyEnd]
	re := regexp.MustCompile(`(?m)^\s*\(\s*(\d+)\s*,\s*(0x[0-9A-Fa-f]+|\d+)\s*\)`)
	matches := re.FindAllStringSubmatch(body, -1)
	expected := map[string]int{"HCOD1": 81, "HCOD2": 81, "HCOD3": 81, "HCOD4": 81, "HCOD5": 81, "HCOD6": 81, "HCOD7": 64, "HCOD8": 64, "HCOD9": 169, "HCOD10": 169, "HCOD11": 289, "HCOD_SF": 121}[name]
	if len(matches) != expected {
		fatalf("table %s: got%d entries want%d", name, len(matches), expected)
	}
	out := make([]entry, 0, len(matches))
	for _, m := range matches {
		out = append(out, entry{bits: m[1], code: m[2]})
	}
	return out
}

func normalizeCode(v string) string {
	if strings.HasPrefix(v, "0x") {
		return strings.ToLower(v)
	}
	return v
}

func decodeTuple(index, dimension, lav int, unsigned bool) [4]int16 {
	modulus, offset := lav+1, 0
	if !unsigned {
		modulus, offset = 2*lav+1, lav
	}
	var out [4]int16
	remaining := index
	for i := dimension - 1; i >= 0; i-- {
		out[i] = int16(remaining%modulus - offset)
		remaining /= modulus
	}
	if remaining != 0 {
		fatalf("tuple index %d exceeds dimension %d/LAV %d", index, dimension, lav)
	}
	return out
}

func mustLocate(rel string) string {
	if root := os.Getenv("GO264_MIT_AAC_REFERENCE"); root != "" {
		return filepath.Join(root, strings.TrimPrefix(rel, "tmp/go264-mit/oxideav-aac/"))
	}
	candidates := []string{
		filepath.Join("/var/home/agent/workspace", rel),
		filepath.Join(mustPackageDir(), "..", "..", "..", "..", "..", "..", rel),
		filepath.Join(mustWorkspaceDir(), rel),
	}
	for _, candidate := range candidates {
		if _, err := os.Stat(candidate); err == nil {
			return candidate
		}
	}
	fatalf("unable to locate %s", rel)
	return ""
}

func mustPackageDir() string {
	wd, err := os.Getwd()
	must(err)
	return wd
}

func mustWorkspaceDir() string {
	wd := mustPackageDir()
	for _, rel := range []string{".", "..", "../..", "../../..", "../../../..", "../../../../..", "../../../../../.."} {
		candidate := filepath.Clean(filepath.Join(wd, rel))
		if _, err := os.Stat(filepath.Join(candidate, "tmp")); err == nil {
			return candidate
		}
	}
	return wd
}

func mustRead(path string) string {
	data, err := os.ReadFile(path)
	must(err)
	return string(data)
}

func must(err error) {
	if err != nil {
		fatalf("%v", err)
	}
}

func fatalf(format string, args ...any) {
	fmt.Fprintf(os.Stderr, format+"\n", args...)
	os.Exit(1)
}
