// Code generated by go-264. DO NOT EDIT.

//go:build amd64

package transform

import "unsafe"

// IDCT4x4_AVX2 performs 4×4 inverse integer DCT using AVX2.
// The block is 16 int16 values in row-major order.
//
//go:noescape
func IDCT4x4_AVX2(block *int16)

// DCT4x4_AVX2 performs 4×4 forward integer DCT using AVX2.
//
//go:noescape
func DCT4x4_AVX2(block *int16)

// HasAVX2 reports whether AVX2 is available.
var HasAVX2 = detectAVX2()

func detectAVX2() bool {
	// CPUID check for AVX2: EAX=7, ECX=0 → EBX bit 5
	return cpuidHasAVX2()
}

//go:noescape
func cpuidHasAVX2() bool

var HasNEON = false

func IDCT4x4_NEON(block *int16) {
	if block == nil {
		return
	}
	IDCT4x4Scalar(unsafe.Slice(block, 16))
}
func DCT4x4_NEON(block *int16) {
	if block == nil {
		return
	}
	DCT4x4Scalar(unsafe.Slice(block, 16))
}
